"""add pwd,posts and comments  migration

Revision ID: 187378d0e559
Revises: 60aa539b6a4a
Create Date: 2018-09-07 18:27:40.857943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187378d0e559'
down_revision = '60aa539b6a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
