"""ffasdtyh

Revision ID: 2a300c1e3da6
Revises: e0e505df14d3
Create Date: 2018-09-08 17:50:49.190106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a300c1e3da6'
down_revision = 'e0e505df14d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'posted')
    # ### end Alembic commands ###
