"""new relationships

Revision ID: 719fbf6f0758
Revises: ea13aaa30241
Create Date: 2018-09-10 19:18:35.994783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719fbf6f0758'
down_revision = 'ea13aaa30241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    # ### end Alembic commands ###
