"""removed category coulumn

Revision ID: 836f2c51dbcd
Revises: b6b473869aea
Create Date: 2018-09-08 13:30:20.382070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836f2c51dbcd'
down_revision = 'b6b473869aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'category')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.add_column('posts', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
