"""add pwd,posts and comments  migration

Revision ID: 8934decef4be
Revises: 187378d0e559
Create Date: 2018-09-07 18:29:12.684874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8934decef4be'
down_revision = '187378d0e559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.String(length=255), nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###
