"""initial migrate

Revision ID: b0be9b7b37fc
Revises: 5e3ca6cea4aa
Create Date: 2018-09-07 11:56:02.535003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0be9b7b37fc'
down_revision = '5e3ca6cea4aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('aiiye', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'aiiye')
    # ### end Alembic commands ###
