"""removed category coulumn

Revision ID: d35223fd2c71
Revises: 836f2c51dbcd
Create Date: 2018-09-08 13:38:52.700420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35223fd2c71'
down_revision = '836f2c51dbcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'categories', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'category')
    op.drop_table('categories')
    # ### end Alembic commands ###
